### ISSUE TITLE
Migrate all tenant DBs at once

### ISSUE THREAD

**Issue by budhajeewa** [a2way-com/laravel-tenant-migrate#2]

**Comment by idan89** [comment]
Has this been implemented? 
Would be awesome to define a prefix for each database, for example migrate all database with **_tenant__**

Thx

**Comment by budhajeewa** [comment]
@idan89 Done.

See: https://github.com/a2way-com/laravel-tenant-migrate/commit/b9ed06c45e79ea556cf16bd7fd1fd3c8f66d033a#diff-04c6e90faac2675aa89e2176d2eec7d8R22
