### ISSUE TITLE
artisan not working for laravel 5

### ISSUE THREAD

**Issue by Jmrich** [a2way-com/laravel-tenant-migrate#5]
After adding A2way\LaravelTenantMigrate\LaravelTenantMigrateServiceProvider to config/app.php providers array, php artisan will not run. I get [BadMethodCallException]  Call to undefined method [package]. If I remove that line from the providers artisan will start working again.

**Comment by budhajeewa** [comment]
@Jmrich : I will take a look at this this weekend and come up with a fix. :smile:

**Comment by budhajeewa** [comment]
I fixed this @Jmrich.

**Comment by Jmrich** [comment]
Cool. Thanks a lot. Is there an option to seed the database with this as
well? Thats the only thing I couldn't find.

On Fri, May 8, 2015 at 8:17 PM, Supun Budhajeewa <notifications@github.com>
wrote:

> I fixed this @Jmrich <https://github.com/Jmrich>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/a2way-com/laravel-tenant-migrate/issues/5#issuecomment-100416936>
> .
>



-- 
John M. Richardson Jr.

**Comment by budhajeewa** [comment]
@Jmrich : Yeah, you can run `db:tenant:seed [connection-name] [database-name]`.

I see this is missing in the `readme.md`, I'll update it soon. :smiley:.
