### ISSUE TITLE
Quick Help on Seeder

### ISSUE THREAD

**Issue by vik0803** [a2way-com/laravel-tenant-migrate#8]
Hi,

First of all, it is a great package that you have designed but I do have 1 question. 

1. As SeedTenantDatabaseCommand is just executing the db:seed via a command db:tenant:seed but what is the case if I wanna give particular class file as an input

The reason is as we release patch update it will surely need a logic that checks the current db version and then apply particular class

Once again thanks in advance.

Vik

**Comment by vik0803** [comment]
Here is something I thought to share. 

`protected function getArguments()
	{
		return array(
			array('connection-name', InputArgument::REQUIRED, 'Tenant connection name.'),
			array('database-name', InputArgument::REQUIRED, 'Tenant database name.'),
			array('class-name', InputArgument::REQUIRED, 'Tenant class name that you want to execute.'),
		);
	}
`
And here is in Fire Function
`
public function fire()
	{
		$connectionName = $this->argument('connection-name');
		$databaseName = $this->argument('database-name');
		$className = $this->argument('class-name');
....
.....
.....
$this->call('db:seed', ['--class' => $className]);
`
Let me know if you think if this can work??

**Comment by budhajeewa** [comment]
Hi @vik0803 , thank you for opening this issue.

Will it be possible for you to send in a PR for this to the `dev` branch?

It might take a _little_ time for me to work on this.

**Comment by budhajeewa** [comment]
@vik0803 : Done.
